using System;
using Unity.Mathematics;
using UnityEngine;
using UnityEngine.Splines;

namespace MotionMatching
{
/// <summary>
/// A <see cref="SplineControlInput"/> whose spline carries pose keypoints: when a prediction horizon
/// lands on a <see cref="SplinePoseKeypoint"/> keypoint, the bone trajectory channels (e.g. the foot
/// keypoint channels) switch on with that keypoint's bone position as the query target. Away from
/// keypoints the channels stay off, so the stage weight-masks them and the search behaves like plain
/// spline following.
/// </summary>
/// <remarks>
/// <para>
/// The facing this reports comes from the keypoints, not from the path tangent. The database bakes
/// its Direction channels as the character's facing, and nothing downstream steers the character
/// toward the controller — <see cref="AnimationTools.MotionSynthesisComponent"/> integrates the
/// matched clip's own yaw rate — so the direction query is the only influence this input has over
/// which way the character ends up facing. Feeding it the direction of travel would fight the foot
/// constraints on any pose whose facing differs from its heading.
/// </para>
/// <para>
/// Assumes the keypoint animation uses the same rig as the motion-matching data, so a channel's bone
/// resolves against the keypoint skeleton.
/// </para>
/// </remarks>
public class SplinePoseKeypointControlInput : SplineControlInput
{
    [Tooltip("Source of the spline and the keypoint poses this input constrains toward.")]
    public SplinePoseKeypoint poseKeypoints;

    [Min(0)]
    [Tooltip("How close, in database frames of travel, a prediction horizon must land to a keypoint " +
             "for its constraint to switch on.")]
    public int activationWindowFrames = 2;

    private bool HasKeypoints => poseKeypoints != null && poseKeypoints.Keypoints.Count > 0;

    /// <summary>
    /// The path comes from the keypoints, which generate it and the constraint targets together, so
    /// there is no container to follow and nothing to keep in sync.
    /// </summary>
    protected override bool HasPath => poseKeypoints != null && poseKeypoints.HasPath;

    protected override float3 SamplePosition(float t) => poseKeypoints.EvaluateWorldPosition(t);

    protected override float PathLength => poseKeypoints != null ? poseKeypoints.WorldLength : 0f;

    /// <summary>
    /// Always null, and refuses assignment out loud: <c>PathFollowingMetric</c> and the benchmark
    /// driver push a container into every spline input they find, and that must not look like it
    /// changed where this one goes.
    /// </summary>
    public override SplineContainer SplineContainer
    {
        get => null;
        set
        {
            if (value == null) return;
            Debug.LogWarning("[SplinePoseKeypointControlInput] Ignoring the assigned SplineContainer: " +
                             "this input follows the path generated by its pose keypoints.", this);
        }
    }

    private void OnValidate()
    {
        // The Inspector writes the inherited field directly and never goes through the property above,
        // so a Spline Container assigned there would sit in the component looking as though it did
        // something. Clear it where it is actually set.
        if (splineContainer == null) return;
        splineContainer = null;
        Debug.LogWarning("[SplinePoseKeypointControlInput] Cleared the assigned Spline Container: this " +
                         "input follows the path generated by its pose keypoints.", this);
    }

    /// <summary>
    /// The path's stored facing rather than the direction it travels in. Overriding here rather than
    /// at <see cref="GetTrajectoryFeature"/> means the trajectory query, the debug gizmos and
    /// <see cref="SplineControlInput.GetCurrentRotation"/> all report the same thing.
    /// </summary>
    protected override float2 SampleDirection(float t, float3 positionAtT)
    {
        if (!HasKeypoints) return base.SampleDirection(t, positionAtT);

        var facing = poseKeypoints.GetWorldFacing(t);
        var flat = new float2(facing.x, facing.z);
        // Falling back costs an extra spline evaluation, so only pay it if the facing is unusable.
        return math.lengthsq(flat) > 1e-8f ? math.normalize(flat) : base.SampleDirection(t, positionAtT);
    }

    public override bool GetBoneTrajectoryFeature(TrajectoryFeatureChannel feature, int index, Transform character,
        Span<float> output)
    {
        if (poseKeypoints == null || feature.featureType != TrajectoryFeatureChannel.Type.Position) return false;

        var pathLength = PathLength;
        if (pathLength <= 1e-5f) return false;

        var tFuture = GetPredictedSplineT(feature.predictionFrames[index]);
        var tolerance = activationWindowFrames * speed / pathLength * DatabaseDeltaTime;
        if (!poseKeypoints.TryGetKeypointNearT(tFuture, tolerance, out var keypoint)) return false;

        var boneIndex = feature.bone?.ResolveIndex(poseKeypoints.Skeleton) ?? -1;
        if (boneIndex < 0) return false;
        if (!poseKeypoints.TryGetWorldBonePosition(keypoint, boneIndex, out var world)) return false;

        // Bake-exact character space: yaw-only rotation, ground-projected origin, Y kept as absolute
        // height — InverseTransformPoint would subtract the transform's Y and apply its scale.
        var forward = math.normalizesafe(new float3(character.forward.x, 0f, character.forward.z), math.forward());
        var local = math.mul(math.inverse(quaternion.LookRotation(forward, math.up())),
            world - new float3(character.position.x, 0f, character.position.z));

        var f = 0;
        if (!feature.zeroX) output[f++] = local.x;
        if (!feature.zeroY) output[f++] = local.y;
        if (!feature.zeroZ) output[f] = local.z;
        return true;
    }

    /// <summary>The start of the path, so a character spawns on it rather than wherever this
    /// GameObject sits.</summary>
    public override float3 GetWorldInitPosition() =>
        HasKeypoints ? poseKeypoints.EvaluateWorldPosition(0f) : base.GetWorldInitPosition();

    /// <summary>The facing the path carries at its start, not the direction it sets off in.</summary>
    public override float3 GetWorldInitDirection() =>
        HasKeypoints ? poseKeypoints.GetWorldFacing(0f) : base.GetWorldInitDirection();
}
}
